Added rebase support to interactive pull

diff --git a/scripts/git-interactive-pull-push b/scripts/git-interactive-pull-push
--- a/scripts/git-interactive-pull-push
+++ b/scripts/git-interactive-pull-push
@@ -62,9 +62,32 @@ if [ -z "$REMOTEKEYS" ]; then
 	exit
 fi
 
+OPTIONS=
+if [ "$ACTION" == pull ]; then
+	OPTIONS="$OPTIONS --ff-only"
+fi
+
 for REMOTE in $(echo $REMOTEKEYS | tr "," " "); do
-	echo git $ACTION "${REMOTES[$REMOTE]}" "$CURRENTBRANCH"
-	git $ACTION "${REMOTES[$REMOTE]}" "$CURRENTBRANCH"
+	echo git $ACTION $OPTIONS "${REMOTES[$REMOTE]}" "$CURRENTBRANCH"
+	RESPONSE="$(git $ACTION $OPTIONS "${REMOTES[$REMOTE]}" "$CURRENTBRANCH" 2>&1)"
+	ACTION_EXIT_CODE="$?"
+	echo "$RESPONSE"
+	if [[ "$ACTION_EXIT_CODE" != 0 ]]; then
+		if echo "$RESPONSE" | grep -q "fatal: Not possible to fast-forward, aborting."; then
+			echo "Fast forward pull failed, you wish to rebase or merge?"
+			echo " 1) rebase merge"
+			echo " 2) normal merge"
+			echo " 3) abort pull"
+			read -p "Action: " NEXT_ACTION
+			if [ "$NEXT_ACTION" == 1 ]; then
+				git $ACTION --rebase "${REMOTES[$REMOTE]}" "$CURRENTBRANCH"
+			fi
+			if [ "$NEXT_ACTION" == 2 ]; then
+				git $ACTION "${REMOTES[$REMOTE]}" "$CURRENTBRANCH"
+			fi
+		fi
+		exit
+	fi
 	if [[ "$ACTION" == "push" && "${REMOTES[$REMOTE]}" != "origin" && "${REMOTES[$REMOTE]}" != "upstream" && "$CURRENTBRANCH" != "--all" ]]; then
 		read -e -p "Send pull request? [y/n] " -i "n" CONFIRM_PULL_REQUEST
 		if [[ "$CONFIRM_PULL_REQUEST" == "y" ]]; then
